---
jobs:
- name: run-billing-diego-staging
  plan:
  - aggregate:
    - get: diego-schedule
      trigger: true
    - get: billing-src
  - task: run-billing-diego
    file: billing-src/diego.yml
    params:
      ES_URI: {{es-uri-staging}}
      BILL_INDEX: {{bill-index-staging}}
      DOC_TYPE: {{doc-type-staging}}
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to run diego billing on staging
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: {{slack-channel}}
      username: {{slack-username}}
      icon_url: {{slack-icon-url}}
  on_success:
    put: slack
    params:
      text: |
        :x: Ran diego billing on staging
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: {{slack-channel}}
      username: {{slack-username}}
      icon_url: {{slack-icon-url}}

- name: run-billing-diego-production
  plan:
  - aggregate:
    - get: diego-schedule
      passed: [run-billing-diego-staging]
      trigger: true
    - get: billing-src
  - task: run-billing-diego
    file: billing-src/diego.yml
    params:
      ES_URI: {{es-uri-production}}
      BILL_INDEX: {{bill-index-production}}
      DOC_TYPE: {{doc-type-production}}
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to run diego billing on production
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: {{slack-channel}}
      username: {{slack-username}}
      icon_url: {{slack-icon-url}}
  on_success:
    put: slack
    params:
      text: |
        :x: Ran diego billing on production
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: {{slack-channel}}
      username: {{slack-username}}
      icon_url: {{slack-icon-url}}

resources:
- name: diego-schedule
  type: cron-resource
  source:
    expression: {{diego-schedule-expression}}
    location: {{diego-schedule-location}}

- name: billing-src
  type: git
  source:
    uri: {{billing-git-url}}
    branch: {{billing-git-branch}}

- name: slack
  type: slack-notification
  source:
    url: {{slack-webhook-url}}

resource_types:
- name: cron-resource
  type: docker-image
  source:
    repository: cftoolsmiths/cron-test

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
